### PR TITLE
Timeline

### PR DESCRIPTION
**Pull request by simonbor**

### CODE REVIEW

**Comment by akariv** [comment]
@simonbor where did my commit go?
I resolved all conflicts with master, and now it's gone... did you force-push to the branch?

**Comment by simonbor** [comment]
I don't know what that mean - force-push. 
I just closed previously pushed request, deleted the branch and pushed a new fixed branch with the same name again. Not good? Teach me what i can do in the next time.

**Comment by akariv** [comment]
Why did you delete the branch then?
I contained some of my work (resolving the conflicts).
Generally speaking, if you want to update the branch, just push your extra
work to it. No need to delete branches or create new PRs...

**Comment by simonbor** [comment]
@akariv On my machine all tests are passes but on dockercloud they failed.
Can you please take a look which exactly tests failed?

**Comment by akariv** [comment]
Dockercloud is currently being decommissioned, don't worry about it.

**Pull request merged**
