### PR TITLE
change search bar

### PR DESCRIPTION
**Pull request by ilyagromzy**
**work in progress, still testing**

### CODE REVIEW

**Comment by akariv** [comment]
@ilyagromzy do you need my assistance in resolving the conflicts?

**Comment by ilyagromzy** [comment]
finished fixes on search drop down. 
- with missing red looking glass svg icon - used png
- down arrows - white and red svgs - used css

merged the conflicted file, but after merge the page didnt work. so i reversed the merge

**Comment by ilyagromzy** [comment]
fixed merge and created another pull request

**Comment by akariv** [comment]
Can you post a link to the other PR?

**Pull request merged**
