### PR TITLE
Replacing SVG spinner with a Font Awesome one.

### PR DESCRIPTION
**Pull request by danielbraun**
This fixes issue #42.
Loading indicator hangs on Mac Safari.
I've replaced the SVG spinner with a Font Awesome spinner.

### CODE REVIEW

**Comment by akariv** [comment]
Great work @danielbraun !

While you're at it, could also replace the loader in the generic item page as well:
https://github.com/OpenBudget/budgetkey-app-generic-item/blob/master/assets/img/loader.svg

?

Thanks!

**Comment by danielbraun** [comment]
Looks like autocomplete/search doesn't work there at all, am I right?
http://next.obudget.org/i/contract-spending/4501330665/0030120602

**Comment by akariv** [comment]
The spinner in this page is not in the search bar, but in the data table at
the bottom of the page.
See for example here:
http://next.obudget.org/i/org/law_mandated_organization/500500046

Try to select different questions in the dropdown at the bottom to see the
spinner in action.

**Comment by danielbraun** [comment]
PR at https://github.com/OpenBudget/budgetkey-app-generic-item/pull/34

**Pull request merged**
